version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "poetry-parser"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ei9h2lg95jza"
s3_prefix = "poetry-parser"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
