#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BASEDIR=$(pwd)
cd $BASEDIR/src/poetry-parser/poetry-parser && npm test
if [ $? -ne 0 ]; then
   exit 1
fi
cd $BASEDIR/src/frontend && npm test && npm run test:e2e
if [ $? -ne 0 ]; then
   exit 1
fi

